name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

env:
  DEPLOY_PATH: tmp
  NODE_VERSION: "22.16.0"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create a folder with all compiled apps and pkgs
        if: github.event.action != 'closed'
        run: |
          mkdir -p ${{ env.DEPLOY_PATH }}
          echo "<!doctype html><html><head><meta charset='utf-8'><title>PR Preview</title></head><body><h1>Previews</h1><ul>" > ${{ env.DEPLOY_PATH }}/index.html
        


      - name: Provide secret props for build
        if: github.event.action != 'closed'
        run: |
          if [ -f secretProps.template.json ]; then
            cp secretProps.template.json secretProps.json
          fi

      - name: Install and Build
        if: github.event.action != 'closed'
        run: ./.github/scripts/build-app.sh
        env:
          TARGET_FOLDER: LimesUI
        continue-on-error: true
   
      - name: Deploy preview
        if: github.event.action != 'closed'
        run: |
          echo "<li><a href='./LimesUI/index.html'> LimesUI </a></li>" >> ${{ env.DEPLOY_PATH }}/index.html
          echo "</ul></body></html>" >> ${{ env.DEPLOY_PATH }}/index.html
        
          